[package]
name = "spotify-mutify"
version = "0.1.0"
authors = ["Thomas McNiven <hello@vevix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
structopt = "0.2"
crossbeam-channel = "0.3.8"
notify = "=5.0.0-pre.1"
directories = "2.0"
external = { git = "https://github.com/CasualX/external", rev = "af1c872" }
pelite = { git = "https://github.com/CasualX/pelite", rev = "155918a" }
failure = "0.1"
