[package]
name = "spotify-mutify"
version = "0.1.0"
authors = ["Thomas McNiven <hello@vevix.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
winapi = "0.3"
crossbeam-channel = "0.3.8"
notify = "=5.0.0-pre.1"
